[contract_store]
# Filesystem contract store configuration. ``type`` controls the active backend.
type = "filesystem"
# Path to the filesystem contract store. Defaults to a "contracts" directory
# inside the current working directory when unset.
root = ""

[auth]
# Optional bearer token required for requests to the backend API.
token = ""

[unity_catalog]
# Disable Unity Catalog tagging by default; enable and supply Databricks
# connection details (profile or host/token) to mirror dataset links into
# catalog table properties.
enabled = false
dataset_prefix = "table:"
workspace_profile = ""
workspace_host = ""
workspace_token = ""
