# Example configuration for the dc43 contracts application.
# Copy this file next to your deployment (e.g. /etc/dc43/contracts-app.toml)
# and update the paths to match your environment. Export the file path via
# `DC43_CONTRACTS_APP_CONFIG=/path/to/contracts-app.toml` before launching the
# demo so the app picks it up, and remember that `docs_chat.api_key_env`
# contains the *name* of the environment variable that stores your secret.

[workspace]
# Location where draft contracts and attachments are stored.
root = "~/dc43/workspace"

[backend]
# Choose between "embedded" (launch the backend locally) or "remote".
mode = "embedded"
# Base URL of the backend when operating in remote mode.
base_url = ""

[backend.process]
# Network settings used when `mode = "embedded"`.
host = "127.0.0.1"
port = 8001
# Optional log level forwarded to the embedded backend (e.g. "info").
log_level = ""

[docs_chat]
# Enable when you want to expose the embedded documentation assistant in the dc43 app.
enabled = false
# The provider powering the chat experience ("openai" is currently supported).
provider = "openai"
# Chat completion model requested from the provider.
model = "gpt-4o-mini"
# Embedding model used to vectorise Markdown documentation.
embedding_model = "text-embedding-3-small"
# Environment variable that stores the API key for the provider.
api_key_env = "OPENAI_API_KEY"
# Override when documentation lives outside the repository checkout.
docs_path = ""
# Override to persist the vector index in a custom directory.
index_path = ""
