[workspace]
# ``root`` defaults to a temporary directory when left empty.
root = ""

[backend]
# Use the in-process backend by default to keep tests lightweight.
mode = "embedded"

[backend.process]
# Settings applied when the contracts CLI spawns a backend.
host = "127.0.0.1"
port = 8001
log_level = ""

[docs_chat]
# Documentation chat is disabled by default. Set ``enabled = true`` and provide
# an API key environment variable when you are ready to use it.
enabled = false
provider = "openai"
model = "gpt-4o-mini"
embedding_model = "text-embedding-3-small"
api_key_env = "OPENAI_API_KEY"
docs_path = ""
index_path = ""
