name: release

concurrency:
  group: release-packages
  cancel-in-progress: false

on:
  push:
    tags:
      - "dc43-v*"
      - "dc43-service-clients-v*"
      - "dc43-service-backends-v*"
      - "dc43-integrations-v*"
      - "dc43-contracts-app-v*"

jobs:
  determine:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.tags.outputs.should_run }}
      canonical_tag: ${{ steps.tags.outputs.canonical }}
      core_tag: ${{ steps.tags.outputs.core_tag }}
      service_clients_tag: ${{ steps.tags.outputs.service_clients_tag }}
      service_backends_tag: ${{ steps.tags.outputs.service_backends_tag }}
      integrations_tag: ${{ steps.tags.outputs.integrations_tag }}
      contracts_app_tag: ${{ steps.tags.outputs.contracts_app_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true

      - name: Identify release tags
        id: tags
        run: |
          set -euo pipefail

          tags=$(git tag --points-at "$GITHUB_SHA" | sort || true)
          if [ -z "$tags" ]; then
            echo "No tags found on commit $GITHUB_SHA" >&2
            exit 1
          fi

          prefixes=(
            "dc43-v"
            "dc43-service-clients-v"
            "dc43-service-backends-v"
            "dc43-integrations-v"
            "dc43-contracts-app-v"
          )
          outputs=(
            "core_tag"
            "service_clients_tag"
            "service_backends_tag"
            "integrations_tag"
            "contracts_app_tag"
          )

          canonical=""
          for i in "${!prefixes[@]}"; do
            prefix="${prefixes[$i]}"
            name="${outputs[$i]}"
            match=$(printf '%s\n' "$tags" | grep "^${prefix}" | head -n1 || true)
            echo "${name}=${match}" >> "$GITHUB_OUTPUT"
            if [ -z "$canonical" ] && [ -n "$match" ]; then
              canonical="$match"
            fi
          done

          if [ -z "$canonical" ]; then
            echo "No recognized release tags found on commit $GITHUB_SHA" >&2
            exit 1
          fi

          should_run=false
          if [ "$canonical" = "$GITHUB_REF_NAME" ]; then
            should_run=true
          fi

          {
            echo "canonical=${canonical}"
            echo "should_run=${should_run}"
          } >> "$GITHUB_OUTPUT"

          if [ "$should_run" != "true" ]; then
            cat <<SUMMARY >> "$GITHUB_STEP_SUMMARY"
### Release run skipped
This workflow run was triggered by `$GITHUB_REF_NAME`.
The canonical tag `$canonical` will execute the release pipeline.
SUMMARY
          fi

  release:
    needs: determine
    if: needs.determine.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare build tooling
        run: |
          python -m pip install --upgrade pip
          pip install packaging build

      - name: Prepare artifact directory
        run: mkdir -p release-artifacts

      - name: Test and build dc43
        if: needs.determine.outputs.core_tag != ''
        env:
          TAG_NAME: ${{ needs.determine.outputs.core_tag }}
          TAG_PREFIX: dc43-v
          PYPROJECT_PATH: pyproject.toml
          DC43_REQUIRE_PYPI: "1"
        run: |
          set -euo pipefail
          pip install -e '.[test]'
          pytest
          python - <<'PY'
import os
import sys
import tomllib

pyproject_path = os.environ["PYPROJECT_PATH"]
tag = os.environ["TAG_NAME"]
prefix = os.environ["TAG_PREFIX"]

with open(pyproject_path, 'rb') as fh:
    version = tomllib.load(fh)["project"]["version"]

expected = f"{prefix}{version}"
if tag != expected:
    print(f"Tag {tag} does not match expected {expected}")
    sys.exit(1)
PY
          rm -rf release-artifacts/dc43
          python -m build --outdir release-artifacts/dc43

      - name: Publish dc43 to PyPI
        if: needs.determine.outputs.core_tag != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: release-artifacts/dc43

      - name: Publish dc43 GitHub release
        if: needs.determine.outputs.core_tag != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.determine.outputs.core_tag }}
          files: release-artifacts/dc43/*
          generate_release_notes: true

      - name: Test and build dc43-service-clients
        if: needs.determine.outputs.service_clients_tag != ''
        env:
          TAG_NAME: ${{ needs.determine.outputs.service_clients_tag }}
          TAG_PREFIX: dc43-service-clients-v
          PYPROJECT_PATH: packages/dc43-service-clients/pyproject.toml
          DC43_REQUIRE_PYPI: "1"
        run: |
          set -euo pipefail
          pip install -e packages/dc43-service-clients[http]
          pytest packages/dc43-service-clients/tests
          python - <<'PY'
import os
import sys
import tomllib

pyproject_path = os.environ["PYPROJECT_PATH"]
tag = os.environ["TAG_NAME"]
prefix = os.environ["TAG_PREFIX"]

with open(pyproject_path, 'rb') as fh:
    version = tomllib.load(fh)["project"]["version"]

expected = f"{prefix}{version}"
if tag != expected:
    print(f"Tag {tag} does not match expected {expected}")
    sys.exit(1)
PY
          rm -rf release-artifacts/dc43-service-clients
          (cd packages/dc43-service-clients && python -m build --outdir ../../release-artifacts/dc43-service-clients)

      - name: Publish dc43-service-clients to PyPI
        if: needs.determine.outputs.service_clients_tag != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: release-artifacts/dc43-service-clients

      - name: Publish dc43-service-clients GitHub release
        if: needs.determine.outputs.service_clients_tag != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.determine.outputs.service_clients_tag }}
          files: release-artifacts/dc43-service-clients/*
          generate_release_notes: true

      - name: Test and build dc43-service-backends
        if: needs.determine.outputs.service_backends_tag != ''
        env:
          TAG_NAME: ${{ needs.determine.outputs.service_backends_tag }}
          TAG_PREFIX: dc43-service-backends-v
          PYPROJECT_PATH: packages/dc43-service-backends/pyproject.toml
          DC43_REQUIRE_PYPI: "1"
        run: |
          set -euo pipefail
          pip install -e packages/dc43-service-clients[http]
          pip install -e packages/dc43-service-backends
          pytest packages/dc43-service-backends/tests
          python - <<'PY'
import os
import sys
import tomllib

pyproject_path = os.environ["PYPROJECT_PATH"]
tag = os.environ["TAG_NAME"]
prefix = os.environ["TAG_PREFIX"]

with open(pyproject_path, 'rb') as fh:
    version = tomllib.load(fh)["project"]["version"]

expected = f"{prefix}{version}"
if tag != expected:
    print(f"Tag {tag} does not match expected {expected}")
    sys.exit(1)
PY
          rm -rf release-artifacts/dc43-service-backends
          (cd packages/dc43-service-backends && python -m build --outdir ../../release-artifacts/dc43-service-backends)

      - name: Publish dc43-service-backends to PyPI
        if: needs.determine.outputs.service_backends_tag != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: release-artifacts/dc43-service-backends

      - name: Publish dc43-service-backends GitHub release
        if: needs.determine.outputs.service_backends_tag != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.determine.outputs.service_backends_tag }}
          files: release-artifacts/dc43-service-backends/*
          generate_release_notes: true

      - name: Test and build dc43-integrations
        if: needs.determine.outputs.integrations_tag != ''
        env:
          TAG_NAME: ${{ needs.determine.outputs.integrations_tag }}
          TAG_PREFIX: dc43-integrations-v
          PYPROJECT_PATH: packages/dc43-integrations/pyproject.toml
          DC43_REQUIRE_PYPI: "1"
        run: |
          set -euo pipefail
          pip install -e packages/dc43-service-clients[http]
          pip install -e packages/dc43-integrations
          pytest packages/dc43-integrations/tests
          python - <<'PY'
import os
import sys
import tomllib

pyproject_path = os.environ["PYPROJECT_PATH"]
tag = os.environ["TAG_NAME"]
prefix = os.environ["TAG_PREFIX"]

with open(pyproject_path, 'rb') as fh:
    version = tomllib.load(fh)["project"]["version"]

expected = f"{prefix}{version}"
if tag != expected:
    print(f"Tag {tag} does not match expected {expected}")
    sys.exit(1)
PY
          rm -rf release-artifacts/dc43-integrations
          (cd packages/dc43-integrations && python -m build --outdir ../../release-artifacts/dc43-integrations)

      - name: Publish dc43-integrations to PyPI
        if: needs.determine.outputs.integrations_tag != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: release-artifacts/dc43-integrations

      - name: Publish dc43-integrations GitHub release
        if: needs.determine.outputs.integrations_tag != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.determine.outputs.integrations_tag }}
          files: release-artifacts/dc43-integrations/*
          generate_release_notes: true

      - name: Test and build dc43-contracts-app
        if: needs.determine.outputs.contracts_app_tag != ''
        env:
          TAG_NAME: ${{ needs.determine.outputs.contracts_app_tag }}
          TAG_PREFIX: dc43-contracts-app-v
          PYPROJECT_PATH: packages/dc43-contracts-app/pyproject.toml
          DC43_REQUIRE_PYPI: "1"
        run: |
          set -euo pipefail
          pip install -e packages/dc43-service-clients[http]
          pip install -e packages/dc43-service-backends[http]
          pip install -e packages/dc43-integrations
          pip install -e packages/dc43-contracts-app[spark]
          pytest packages/dc43-contracts-app/tests
          python - <<'PY'
import os
import sys
import tomllib

pyproject_path = os.environ["PYPROJECT_PATH"]
tag = os.environ["TAG_NAME"]
prefix = os.environ["TAG_PREFIX"]

with open(pyproject_path, 'rb') as fh:
    version = tomllib.load(fh)["project"]["version"]

expected = f"{prefix}{version}"
if tag != expected:
    print(f"Tag {tag} does not match expected {expected}")
    sys.exit(1)
PY
          rm -rf release-artifacts/dc43-contracts-app
          (cd packages/dc43-contracts-app && python -m build --outdir ../../release-artifacts/dc43-contracts-app)

      - name: Publish dc43-contracts-app to PyPI
        if: needs.determine.outputs.contracts_app_tag != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: release-artifacts/dc43-contracts-app

      - name: Publish dc43-contracts-app GitHub release
        if: needs.determine.outputs.contracts_app_tag != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.determine.outputs.contracts_app_tag }}
          files: release-artifacts/dc43-contracts-app/*
          generate_release_notes: true
