name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history
          tags: true
      - name: Ensure tag on main
        run: |
          echo $GITHUB_SHA
          git --no-pager branch --contains "$GITHUB_SHA"
          if ! git --no-pager branch --contains "$GITHUB_SHA" | grep -q "main"; then
            echo "Tag must point to a commit on main"
            exit 1
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test]' build
      - name: Run tests
        run: pytest
      - name: Check version matches tag
        run: |
          python - <<'PY'
          import tomllib, os, sys
          with open('pyproject.toml','rb') as f:
              version = tomllib.load(f)['project']['version']
          tag = os.environ['GITHUB_REF'].split('/')[-1]
          if f"v{version}" != tag:
              print(f"Tag {tag} does not match version {version}")
              sys.exit(1)
          PY
      - name: Build package
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
